### ISSUE TITLE
Connection via SSH tunnel

### ISSUE THREAD

**Issue by slashercopec** [antonwierenga/activemq-cli#9]
Hi,

I'm trying to connect to my ActiveMQ broker running in my JBoss Fuse 6.0 container. The server I am now attempting to connect to is firewalled but does allow traffic on port 22 and hence I am trying to connect using ssh tunnelling. My ports are: jndi: 1100, jmx: 44445, amq: 61618 and I have ssh tunnels set up for all of these.

So although the broker is remote my jmxurl and amqurl in activemq-cli.config are set to use 127.0.0.1. 

However when I try and connect to the broker with activemq-cli I get an error:
Failed to connect to broker:Connection refused to host: x.x.x.x; nested exception is:
java.net.ConnectionEexception: Connection timed out: connect 
Where x.x.x.x is the (firewalled) IP address of my broker host.

I'm presuming that this IP address is somehow passed back in a JNDI call as otherwise how would activemq-cli know about it? 
So my question is - what is the call that activemq-cli is trying to make to this IP address and is there a way to force activemq-cli to connect to 127.0.0.1 (where the ssh tunnel is) instead?

Thanks

**Comment by antonwierenga** [comment]
> I'm presuming that this IP address is somehow passed back in a JNDI call as otherwise how would activemq-cli know about it?

Correct

>and is there a way to force activemq-cli to connect to 127.0.0.1 (where the ssh tunnel is) instead?
Yes. On the JBoss Fuse server you can configure the host name that is communicated back to the clients with the VM argument 'java.rmi.server.hostname'

I encountered the same issue when trying to connect to ActiveMQ that runs in a Docker on a remote host. ActiveMQ CLI tried to connect to the internal docker IP address instead of the IP address of the Docker's host.

After configuring java.rmi.server.hostname for ActiveMQ I was able to connect.

See my [docker-activemq-jmx](https://github.com/antonwierenga/docker-activemq-jmx/blob/master/Dockerfile) project for the ActiveMQ changes I had to make to be able to connect with ActiveMQ CLI to ActiveMQ (running in a Docker on a remote host).

**Comment by slashercopec** [comment]
Thanks for your help again..
I have managed to create my Fuse karaf container (which runs ActiveMQ) using the java.rmi.server.hostname parameter and now get the hostname back from the JNDI call. Adding this hostname to my hosts file such that it resolves to 127.0.0.1 then allows me to use the SSH tunnelling that I have set up. 
All working fine now.
